/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as Home2RouteImport } from './routes/home-2'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as Products2IndexRouteImport } from './routes/products-2.index'
import { Route as Products2CategoryRouteImport } from './routes/products-2.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Home2Route = Home2RouteImport.update({
  id: '/home-2',
  path: '/home-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const Products2IndexRoute = Products2IndexRouteImport.update({
  id: '/products-2/',
  path: '/products-2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Products2CategoryRoute = Products2CategoryRouteImport.update({
  id: '/products-2/$category',
  path: '/products-2/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-2': typeof Home2Route
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/products-2/$category': typeof Products2CategoryRoute
  '/products-2/': typeof Products2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-2': typeof Home2Route
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/products-2/$category': typeof Products2CategoryRoute
  '/products-2': typeof Products2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-2': typeof Home2Route
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/products-2/$category': typeof Products2CategoryRoute
  '/products-2/': typeof Products2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/home-2'
    | '/products'
    | '/services'
    | '/products-2/$category'
    | '/products-2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/home-2'
    | '/products'
    | '/services'
    | '/products-2/$category'
    | '/products-2'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/home-2'
    | '/products'
    | '/services'
    | '/products-2/$category'
    | '/products-2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  Home2Route: typeof Home2Route
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRoute
  Products2CategoryRoute: typeof Products2CategoryRoute
  Products2IndexRoute: typeof Products2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-2': {
      id: '/home-2'
      path: '/home-2'
      fullPath: '/home-2'
      preLoaderRoute: typeof Home2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-2/': {
      id: '/products-2/'
      path: '/products-2'
      fullPath: '/products-2/'
      preLoaderRoute: typeof Products2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-2/$category': {
      id: '/products-2/$category'
      path: '/products-2/$category'
      fullPath: '/products-2/$category'
      preLoaderRoute: typeof Products2CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  Home2Route: Home2Route,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRoute,
  Products2CategoryRoute: Products2CategoryRoute,
  Products2IndexRoute: Products2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
